#!/bin/bash -e

ROOT=$(cd "$(dirname "$0")/.."; pwd)
cd "$ROOT"

#============================================================
#   Build Projucer
#============================================================
echo "Building Projucer and creating projects"
PROJUCER_ROOT=$ROOT/modules/juce/extras/Projucer/Builds/MacOSX
PROJUCER_APP=$PROJUCER_ROOT/build/Release/Projucer.app/Contents/MacOS/Projucer
cd "$PROJUCER_ROOT"
xcodebuild -configuration Release LLVM_LTO=NO


#============================================================
#   Update PJ project and re-save
#============================================================
PLUGINVAL_PROJECT="$ROOT/pluginval.jucer"
#$PROJUCER_APP --set-version "0.1.0" $PLUGINVAL_PROJECT
$PROJUCER_APP --bump-version $PLUGINVAL_PROJECT
$PROJUCER_APP --resave $PLUGINVAL_PROJECT

VERSION=$($PROJUCER_APP --get-version $PLUGINVAL_PROJECT)
cd "$ROOT"
git commit -a -m "Version $VERSION"
git tag "v$VERSION"
git push origin v$VERSION
git push
