#!/bin/bash -e

ROOT=$(cd "$(dirname "$0")/../"; pwd)
BIN="$ROOT/bin"
cd "$BIN"

if [ ! -d pluginval.app ]; then
	echo "Unable to find macOS build"
	exit 1
fi

if [ ! -f pluginval.exe ]; then
	echo "Unable to find Windows build"
	exit 1
fi

if [ ! -f pluginval ]; then
	echo "Unable to find Linux build"
	exit 1
fi

VERSION_NUM=$(/usr/libexec/PlistBuddy -c "Print CFBundleVersion" "pluginval.app/Contents/Info.plist")

if [ $? -ne 0 ]; then
	echo "Unable to find version num"
	exit 1
fi

#===============================================================
echo "Createing assets: $VERSION_NUM"
rm -rf assets
mkdir -p assets

zip -r assets/pluginval_v"$VERSION_NUM"_macOS.zip pluginval.app/
zip assets/pluginval_v"$VERSION_NUM"_Windows.zip pluginval.exe
zip assets/pluginval_v"$VERSION_NUM"_Linux.zip pluginval


#===============================================================
echo "Creating latest release"
cd assets

cp pluginval_v"$VERSION_NUM"_macOS.zip pluginval_macOS.zip
cp pluginval_v"$VERSION_NUM"_Windows.zip pluginval_Windows.zip
cp pluginval_v"$VERSION_NUM"_Linux.zip pluginval_Linux.zip
