#!/bin/bash -e

ROOT=$(cd "$(dirname "$0")/.."; pwd)

if [ -z "$ROOT" ]; then
	echo "ERROR: Unknown workspase"
	exit 1
fi

PROJECT_NAME=pluginval
DEPLOYMENT_DIR="$ROOT/bin/linux"

BINARY_NAME="$PROJECT_NAME"
APP_NAME=$BINARY_NAME
APP_FILE=$ROOT/Builds/LinuxMakefile/build/$APP_NAME

echo "\n=========================================="
echo "\nRoot dir: $ROOT"

#============================================================
#   Build Projucer and generate projects
#============================================================
echo "Building Projucer and creating projects"
PROJUCER_ROOT=$ROOT/modules/juce/extras/Projucer/Builds/LinuxMakefile
PROJUCER_EXE=$PROJUCER_ROOT/build/Projucer
cd "$PROJUCER_ROOT"
#make clean
make CONFIG=Release -j4

# Resave project
"$PROJUCER_EXE" --resave "$ROOT/$PROJECT_NAME.jucer"


#============================================================
#   Add VST2 capabilities
#============================================================
if [ -d "$VST2_SDK_DIR" ]; then
	echo "Modifying jucer project for VST2 support"

	sed -i.bak s/'headerPath="..\/..\/modules\/juce\/modules\/juce_audio_processors\/format_types\/VST3_SDK"/headerPath="..\/..\/modules\/juce\/modules\/juce_audio_processors\/format_types\/VST3_SDK;"$VST2_SDK_DIR""/' "$ROOT/$PROJECT_NAME.jucer"
	sed -i.bak s/'<JUCEOPTIONS JUCE_PLUGINHOST_AU="1"/<JUCEOPTIONS JUCE_PLUGINHOST_VST="1" JUCE_PLUGINHOST_AU="1"/' "$ROOT/$PROJECT_NAME.jucer"

	# Resave project
	"$PROJUCER_EXE" --resave "$ROOT/$PROJECT_NAME.jucer"
else
	echo "Not building with VST2 support. To enable VST2 support, set the VST2_SDK_DIR environment variable"
fi


#============================================================
#   Build projects
#============================================================
cd "$ROOT/Builds/LinuxMakefile"
rm -rf $ROOT/Builds/LinuxMakefile/build/
#make clean
make CONFIG=Release -j4


#============================================================
#   Copy to deployment directory
#============================================================
cd "$ROOT"
rm -rf "$DEPLOYMENT_DIR"
mkdir -p "$DEPLOYMENT_DIR"

echo "\nDeploying to: " $DEPLOYMENT_DIR
mv -fv "$APP_FILE" "$DEPLOYMENT_DIR/$APP_NAME"
